---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: endgame-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: endgame.thecasualcoder.in
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
