---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: endgame-basic-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: basic
subjects:
- kind: ServiceAccount
  name: endgame
  namespace: default

